language: node_js
node_js:
  - "stable"
  - "6"
  - "4"
  - "0.12"
script: npm test
after_success:
  - npm install istanbul mocha-lcov-reporter coveralls codacy-coverage codeclimate-test-reporter
  - ./node_modules/.bin/istanbul cover ./node_modules/.bin/_mocha -- --recursive --reporter dot
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls || true
  - cat ./coverage/lcov.info | ./node_modules/.bin/codacy-coverage || true
  - cat ./coverage/lcov.info | ./node_modules/.bin/codeclimate-test-reporter || true
